### ISSUE TITLE
users can't get all data

### ISSUE THREAD

**Issue by mkieser** [gordonfn/datastreamr#4]
I think this line is preventing users from fetching all of the data. The default for "top" is NULL which is supposed to fetch all the data, but when `top <- NULL` this line sets `top <- 1000` which contradicts the intent and only allows one to fetch the top 1000 records.

https://github.com/gordonfn/datastreamr/blob/01451164f24b04f23d62badfd433d0e50ad46718/R/datastreamr.R#L36

**Comment by patrickleclair-GORDONFN** [comment]
The reason why top is set to `1000` is because if it is not set, the system auto sets it to `10` which makes downloading large amounts of data very time intensive. You'll notice on line 37 it also sets `all_data <- TRUE` which then flags it to run `get_all_data` instead of `get_data`. This means that while the top is set to 1000, that is for each request and that it will continuing running next links until there is no more data to download.

 I did notice, however, that when trying to run it with `top<-1000` I did get a timeout error, so I will look into lowering this to a number that still allows for data to be downloaded, but allows for more to be downloaded at a time than 10.

**Comment by mkieser** [comment]
@patrickleclair-GORDONFN How does one download all the data for a particular characteristic? I'm trying this command but I only get 1000 records: `ds_records(pat, select = c("Id", "MonitoringLocationName", "MonitoringLocationLatitude", "MonitoringLocationLongitude", "ActivityStartDate", "CharacteristicName", "ResultValue", "DatasetName"), filter = c("CharacteristicName = Dissolved oxygen (DO)"))`

**Comment by patrickleclair-GORDONFN** [comment]
@mkieser I looked into it and the issue is with the `nextlink` provided by the API. I have submitted an issue related to that and will let you know when it is resolved.

**Comment by patrickleclair-GORDONFN** [comment]
Issue with nextlink resolved
